# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AlarmEventInfo(Model):
    """Represents the information needed when generating an AlarmEvent for an
    Alarm.

    :param message: The Message to be given with the generated AlarmEvent.
    :type message: str
    :param type: The Type of to be given with the generated AlarmEvent.
    :type type: str
    :param priority: The Priority to be given to the genreated AlarmEvent.
    :type priority: int
    """

    _attribute_map = {
        'message': {'key': 'Message', 'type': 'str'},
        'type': {'key': 'Type', 'type': 'str'},
        'priority': {'key': 'Priority', 'type': 'int'},
    }

    def __init__(self, *, message: str=None, type: str=None, priority: int=None, **kwargs) -> None:
        super(AlarmEventInfo, self).__init__(**kwargs)
        self.message = message
        self.type = type
        self.priority = priority
