# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ContainerModel(Model):
    """A Container is the parent for other types; namely Value, Alarm, Container,
    Trend, and Enum.

    :param name: Name of the Container.
    :type name: str
    :param description: Optional description of the Container.
    :type description: str
    :param type: Specifies the type of the Container. Possible values include:
     'Folder', 'Server', 'Device', 'Structure', 'Service'
    :type type: str or ~ewsrestgatewayswagger.models.enum
    :param parent_id: Id of the Container which the Container is found in.
    :type parent_id: str
    :param id: Case sensitive identifier for the entity.
    :type id: str
    """

    _attribute_map = {
        'name': {'key': 'Name', 'type': 'str'},
        'description': {'key': 'Description', 'type': 'str'},
        'type': {'key': 'Type', 'type': 'str'},
        'parent_id': {'key': 'ParentId', 'type': 'str'},
        'id': {'key': 'Id', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(ContainerModel, self).__init__(**kwargs)
        self.name = kwargs.get('name', None)
        self.description = kwargs.get('description', None)
        self.type = kwargs.get('type', None)
        self.parent_id = kwargs.get('parent_id', None)
        self.id = kwargs.get('id', None)
