# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TrendSampleModel(Model):
    """A TrendSample represents the value and state for Value at a given point in
    time belonging to a specific Trend.

    :param trend_id: Id of the Trend this is a sample for.
    :type trend_id: str
    :param value: Value of the Trend.Value at the time of the sample.
    :type value: str
    :param state: State of the Trend.Value at the time of the sample. Possible
     values include: 'Good', 'Uncertain', 'Forced', 'Offline', 'Error'
    :type state: str or ~ewsrestgatewayswagger.models.enum
    :param sample_date: DateTime in UTC when the sample was created.
    :type sample_date: datetime
    :param id: Case sensitive identifier for the entity.
    :type id: str
    """

    _attribute_map = {
        'trend_id': {'key': 'TrendId', 'type': 'str'},
        'value': {'key': 'Value', 'type': 'str'},
        'state': {'key': 'State', 'type': 'str'},
        'sample_date': {'key': 'SampleDate', 'type': 'iso-8601'},
        'id': {'key': 'Id', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(TrendSampleModel, self).__init__(**kwargs)
        self.trend_id = kwargs.get('trend_id', None)
        self.value = kwargs.get('value', None)
        self.state = kwargs.get('state', None)
        self.sample_date = kwargs.get('sample_date', None)
        self.id = kwargs.get('id', None)
